# Generated by Django 3.2.3 on 2021-05-17 16:46

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_product_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to=auction.models.image_path),
        ),
    ]
